### ISSUE TITLE
Event link should be parsed from summary

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/drupal-module-calendar#2]
User should be able to provide a url in the summary that we use to draw a link around the event when it's rendered by Drupal.

The link should just be a bare URL, not an href tag.  We'll use regex to grab the URL out of the event summary.

**Comment by charlesbrandt** [comment]
I would be ok to put the requirement that the URL be on the first line of the summary, if that would help with parsing. If not, I think we should make sure to always choose the first URL, if there is more than one.
