### ISSUE TITLE
Link in description is not added correctly

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-module-calendar#6]
Currently, the [City Holiday page](https://bloomington.in.gov/city/holidays) has an upcoming event listed for MLK day. I tried to add a link in the description of the event to link to: 

https://bloomington.in.gov/mlk-day

When it renders on the drupal site, the event block is incorrectly linked to:

https://www.google.com/url?q=https

**Comment by inghamn** [comment]
We are using regex to try to pull links out of the description.  It looks like the regex is not including uppercase characters.  So, urls with upper case characters are getting butchered.

**Comment by inghamn** [comment]
https://github.com/City-of-Bloomington/drupal-module-calendar/issues/6

**Comment by inghamn** [comment]
Also affects  https://github.com/City-of-Bloomington/drupal-theme-cob/issues/202
